name: Deploy new release to production

on: [ workflow_dispatch ]

#on:
#  push:
#    branches:
#      - master
#    tags:
#      - '*'

env:
  API_SERVER_PORT: 3000
  API_HOST: 127.0.0.1
  BEARER_TOKEN: ${{ secrets.TWITTER_API_TOKEN }}
  BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Compose
        run: |
          docker compose build
          mkdir images
          docker save -o images/nsfw_twitter.tar nsfw_twitter-api nsfw_twitter-t_bot
          gzip nsfw_twitter.tar

      - name: Transfer images to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: root
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          source: images/
          target: /root/images

      - name: SSH to server and restart the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: root
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          script: |
            docker compose down
            cd /root/images
            docker load < nsfw_twitter.tar.gz
            docker compose up --detach
            rm nsfw_twitter.tar.gz